name: ciptakarya
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 3.0.1
  flutter_native_splash: 2.2.3
  flutter_launcher_icons: ^0.9.2
  firebase_auth: 3.3.19
  firebase_core: ^1.17.0
  flutter_svg: ^1.0.3
  lottie: ^1.3.0
  internet_connection_checker: ^0.0.1+4
  firebase_storage: ^10.2.16
  cloud_firestore: ^3.1.16
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  path_provider: ^2.0.10
  animate_do: ^2.1.0
  flutter_story_list: ^1.0.4+2
  story: ^0.7.0
  story_view: ^0.13.2
  dismissible_page: ^0.7.2
  zoom_pinch_overlay: ^1.2.0
  shimmer: ^2.0.0
  insta_like_button: ^0.1.1
  pdf: ^3.8.1
  open_file: ^3.2.1
  flutter: 
    sdk: flutter
  google_sign_in: ^5.3.3
  flutter_carousel_widget: ^1.1.0
  introduction_slider: ^1.0.0


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

flutter_native_splash: 
  color: '#ffffff'
  image: assets/Ciptakarya.png
  android_12: null

flutter_icons: 
  android: launcher_icon
  image_path: assets/Ciptakarya.png

