// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwqow78OQOZsdsovqRVt7QllazZtw4UKw',
    appId: '1:889331242884:web:80a412017ea1d89b082fd1',
    messagingSenderId: '889331242884',
    projectId: 'sicika-31a86',
    authDomain: 'sicika-31a86.firebaseapp.com',
    storageBucket: 'sicika-31a86.appspot.com',
    measurementId: 'G-2VEBYCJBDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBye7JzYJ75VI-VRsmMTnO0uoyuMZocXBU',
    appId: '1:889331242884:android:88a84029050d004d082fd1',
    messagingSenderId: '889331242884',
    projectId: 'sicika-31a86',
    storageBucket: 'sicika-31a86.appspot.com',
  );
}
